/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed-variant": "#0b513d",
        "inverse-primary": "#bec6e0",
        "surface-container-highest": "#d3e4fe",
        "on-tertiary": "#ffffff",
        "tertiary-fixed": "#e0e3e5",
        "surface-container-low": "#eff4ff",
        "tertiary-container": "#191c1e",
        "on-primary": "#ffffff",
        "on-tertiary-container": "#818486",
        "error-container": "#ffdad6",
        "inverse-on-surface": "#eaf1ff",
        "inverse-surface": "#213145",
        "on-secondary": "#ffffff",
        "outline-variant": "#c6c6cd",
        "secondary": "#2b6954",
        "outline": "#76777d",
        "background": "#f8f9ff",
        "on-error": "#ffffff",
        "on-secondary-fixed": "#002117",
        "secondary-fixed-dim": "#95d3ba",
        "surface-tint": "#565e74",
        "secondary-container": "#adedd3",
        "on-primary-fixed": "#131b2e",
        "on-secondary-container": "#306d58",
        "on-tertiary-fixed-variant": "#444749",
        "primary-container": "#131b2e",
        "tertiary-fixed-dim": "#c4c7c9",
        "surface-dim": "#cbdbf5",
        "secondary-fixed": "#b0f0d6",
        "on-surface-variant": "#45464d",
        "surface-variant": "#d3e4fe",
        "surface-container-high": "#dce9ff",
        "on-primary-fixed-variant": "#3f465c",
        "surface-container": "#e5eeff",
        "on-error-container": "#93000a",
        "on-tertiary-fixed": "#191c1e",
        "on-background": "#0b1c30",
        "primary-fixed": "#dae2fd",
        "surface": "#f8f9ff",
        "surface-container-lowest": "#ffffff",
        "on-primary-container": "#7c839b",
        "primary": "#000000",
        "error": "#ba1a1a",
        "tertiary": "#000000",
        "primary-fixed-dim": "#bec6e0",
        "surface-bright": "#f8f9ff",
        "on-surface": "#0b1c30"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "base": "8px",
        "margin-mobile": "20px",
        "container-max": "1280px",
        "margin-desktop": "64px",
        "gutter": "24px",
        "section-gap": "80px"
      },
      fontFamily: {
        "headline-sm": ["Playfair Display"],
        "body-lg": ["Inter"],
        "interactive": ["Inter"],
        "label-caps": ["Inter"],
        "headline-md": ["Playfair Display"],
        "body-sm": ["Inter"],
        "display-lg": ["Playfair Display"],
        "body-md": ["Inter"],
        "display-lg-mobile": ["Playfair Display"]
      },
      fontSize: {
        "headline-sm": ["24px", { "lineHeight": "1.4", "fontWeight": "600" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "interactive": ["14px", { "lineHeight": "1", "fontWeight": "500" }],
        "label-caps": ["12px", { "lineHeight": "1", "letterSpacing": "0.1em", "fontWeight": "600" }],
        "headline-md": ["32px", { "lineHeight": "1.3", "fontWeight": "600" }],
        "body-sm": ["14px", { "lineHeight": "1.4", "fontWeight": "400" }],
        "display-lg": ["48px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "body-md": ["16px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "display-lg-mobile": ["32px", { "lineHeight": "1.2", "fontWeight": "700" }]
      }
    },
  },
  plugins: [],
}
